#!/bin/bash

function create_container() {
    # TODO(Terry): Update `install-docker.sh` to share /home/$(id -un) with docker
    # terry@Terrys-MBP race_ubuntu % ./race_ubuntu start
    # Error response from daemon: Mounts denied:
    # The path /home/terry/race is not shared from the host and is not known to Docker.
    # You can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing.
    # See https://docs.docker.com/desktop/settings/mac/#file-sharing for more info.
    # Error: failed to start containers: Terrys-MBP
    docker create \
        --interactive \
        --name=$1 \
        --hostname=$(hostname) \
        --network=host \
        --volume=/Users/$(id -un)/race:/home/race:rw \
        race_ubuntu:latest
}

function start_container() {
    docker start $1
}

function stop_container() {
    docker stop $1
}

function remove_container() {
    docker rm $1
}

function help() {
    echo "Usage: $0 {create|start|stop|rm} [container_name]"
}

function main() {
    local container_name=$(id -un)
    if [[ $# -gt 2]]; then
        container_name="$1"
        shift
    fi
    case $1 in
    create)
        create_container container_name
        ;;
    start)
        start_container container_name
        ;;
    stop)
        stop_container container_name
        ;;
    rm)
        remove_container container_name
        ;;
    help)
        help
        ;;
    *)
        echo "Invalid command"
        help
        exit 1
        ;;
    esac
}

main "$@"
